# Generated by Django 5.2.7 on 2025-10-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_name',
        ),
    ]
